### PR TITLE
Added cover control

### PR DESCRIPTION
**Pull request by yaccri**
Also added unique_id to lights and covers.
Also tried to create a device from the cover (using device_info) but this part doesn't work

### CODE REVIEW

**Comment by zilvinasbin** [comment]
Merged cover control

**Comment by dnouls** [comment]
Any explanation on how I go about to configure a cover in home assistant ? It is a complete mystery to me!

**Comment by yaccri** [comment]
Here's an example from 'configuration.yaml':
cover:
  - platform: domintell
    devices:
      - type: TRV
        module: 931
        channel: 1
        name: Domintell_Shutter_1      
        location: Home
      - type: TRV
        module: 931
        channel: 2
        name: Domintell_Shutter_2      
        location: Home

**Comment by yaccri** [comment]
Note that the editor here automatically converted the minus sign to a bullet.
Use the minus sign in your configuration.yaml.

**Comment by dnouls** [comment]
Does not work. When I try to control one of the device I get an error: Failed to call service cover/open_cover. 'DTRV01Module' object has no attribute 'open_cover

**Comment by yaccri** [comment]
Maybe you're not pulling the latest python-domintell version.
To test it, try to change the requirements line in 'manifest.json' to:
  "requirements": ["ya-domintell==0.0.8"],

Reboot and test.

**Comment by dnouls** [comment]
Yes that worked. 
But I guess we need a new release for python-domintell then ?

**Comment by yaccri** [comment]
I'm glad that it works.
 
The author, shamanenas, merged the changes to python-domintell, but maybe he didn't increase the version number.
It needs to be done both in python-domintell and in has_domintell.

**Comment by zilvinasbin** [comment]
Hi,
Sorry guys absolutely forgot to update dependencies and package on PyPI package. I did it now and everything shall work.  
Super buzzy days right now. Finishing one project and digging into the research of a new one :)

**Comment by dnouls** [comment]
No problem. I just reinstalled with the latest sources and now it works without modification.
There is however a small glitch: when I restart HA the current state of my screens is wrongly reported as closed.
This is visible in my HomeKit (using it as my main controller) since I see all my screens as closed. 
When I then press to open, nothing happens (which is normal) and after that the state is correct and changes with interactions. So I am guess that the initial state is probably not retrieved.

Thanks for the help! I appreciate this!

**Comment by yaccri** [comment]
You are right. The initial state is unknown.
I don't think that there's a way to know it.

**Comment by zilvinasbin** [comment]
If I remember it right Domintell can only provide information if a particular relay of DTRV is open or closed. there is no data about and end positions. I may be wrong.
what you can do to investigate it. 
Connect to DETH with Hercules or other similar UDP client and send a &PING command. it should output the current state of all modules. look what you get for `TRV`. 

I added protocol datasheet [here](https://github.com/shamanenas/python-domintell/blob/master/docs/DS_RS232_ETH_Interfaces_v1_27_02.pdf)

**Pull request merged**
